### ISSUE TITLE
Implement fuzzy finder as default filter for Select/MultiSelect

### ISSUE THREAD

**Issue by mikaelmello** [mikaelmello/inquire#162]
**Is your feature request related to a problem? Please describe.**

Fuzzy finder is very valuable, and I don't think it'd imply in a significant performance cost at runtime.

**Comment by Baarsgaard** [comment]
Hi, I am currently taking a stab at implementing this as I really want to make use of it.
I have tried forcing it in by writing a filter using fuzzy_matcher, but it's worth next to nothing without the ability to sort the `options` list.

I'm currently running into some decisions I would like your input on.
In order to support a fuzzy filter, it's necessary to sort the list of `options`.

I could implement a separate function like `Filter<'a, &T>` which takes the list of options and replaces `self.options` with the return value.

The issue with this approach would be when and how to handle filter vs the new ranking/matcher function.
Should the list of `options` be both filtered and ranked or should filter and ranking/matching be mutually exclusive.

Alternatively, I would suggest changing the `Filter<'a, &T>` function signature from:
```rs
pub type Filter<'a, T> = &'a dyn Fn(&str, &T, &str, usize) -> bool;
```
And give full access to the entire list of options
```rs
pub type Filter<'a, T> = &'a dyn Fn(&str, &'a Vec<&T>) -> Vec<&'a T>;

// Alternatively
pub type Filter<'a, T> = &'a dyn Fn(&str, &'a Vec<&T>);
```

This would allow users to implement whatever filter/ordering logic they want, as well as allowing the use of a default fuzzy filter.

Lastly, it would be simple to add a feature flag enabling the fuzzy vs contains default filter that is currently in place allowing users to not include the `fuzzy_matcher` library

**Comment by Baarsgaard** [comment]
Since #176 is merged, could this be closed?

**Comment by mikaelmello** [comment]
Yes, thanks! I'll work over wrapping-up everything that's been merged into a release
