### ISSUE TITLE
help: how can I validate this? 

### ISSUE THREAD

**Issue by greweln** [mikaelmello/inquire#165]
Can anyone give me a hand with this please, I can't seem to find a way to make this work.
Basically, I need to validate if a key exists in a HashMap(self.account):
```    fn create(&mut self) {
        let val = Text::new("New account name")
            .with_validator(|input: &str| {
                if self.account.contains_key(input) {
                    Ok(Validation::Invalid("Account name exists!".into()))
                } else {
                    Ok(Validation::Valid)
                }
            })
            .prompt()
            .unwrap();
    }
```
It gives me this error:

![screenshot](https://github.com/mikaelmello/inquire/assets/78338967/9ac8f019-8c63-4165-a04f-6c8c7b387a8a)

**Comment by mikaelmello** [comment]
Currently, validators must have a static lifetime, so you can't capture data that is bound to live less.

A quick fix is to clone the hashmap so it's moved instead of borrowed. It'd be good to allow the validators to borrow values like that, I'm still grappling with a good long-term design for inquire
