### ISSUE TITLE
Doubt about the example provided in the documentation

### ISSUE THREAD

**Issue by alk0x1** [mikaelmello/inquire#173]
I'm getting this infer error following the "Simple Example": https://docs.rs/inquire/latest/inquire/
![image](https://github.com/mikaelmello/inquire/assets/59076746/32ec314e-fd36-46fa-aff0-72c381a84f21)

But when I put the ``let status = Text::new("What are you thinking about?")
        .with_validator(validator)
        .prompt();``
![image](https://github.com/mikaelmello/inquire/assets/59076746/7c259523-4f0e-4e6a-9825-4cfedf6394d9)

The error goes away. Why this happen?

**Comment by DefaultSimon** [comment]
The "issue" here seems to be that in Rust, you can't annotate closure return types (as far as I'm aware). Rust is, however, pretty good at inferring those types, including the return type of our closure here. This is why the error disappears when you call `Text::with_validator`.

Look at the [bounds for `V`](https://docs.rs/inquire/latest/inquire/struct.Text.html#method.with_validator) where `StringValidator` is mentioned, then follow it to [this `StringValidator` impl](https://docs.rs/inquire/latest/inquire/validator/trait.StringValidator.html#impl-StringValidator-for-F). This means that `with_validator` expects a function or a closure that returns a `Result<Validation, CustomUserError>`.

Let's look at the the closure body:
```rust
let validator = |input: &str| {
    if input.chars().count() > 140 {
        Ok(Validation::Invalid(
            "You're only allowed 140 characters.".into(),
        ))
    } else {
        Ok(Validation::Valid)
    }
};
```

So we're returning a `Result` and it just so happens that it's always a `Result::Ok`. This means that, before adding the `with_validator` call, the compiler doesn't know what the type of the `Err` variant of our result is, because we never specify it.

---

Personally, I don't think this is a huge issue, as these validator closures are pretty much always used a bit later in the code, making the error go away.

However, we can still solve this in one of two ways:

1. Specify the full `Result` return type in the closure *just once*, like so:
```rust
let validator = |input: &str| {
    if input.chars().count() > 140 {
        Result::<Validation, CustomUserError>::Ok(Validation::Invalid(
            "You're only allowed 140 characters.".into(),
        ))
    } else {
        Ok(Validation::Valid)
    }
};
```

2. Specify the return type, but that means we need to use a function instead:
```rust
fn validator(input: &str) -> Result<Validation, CustomUserError> {
    if input.chars().count() > 140 {
        Ok(Validation::Invalid(
            "You're only allowed 140 characters.".into(),
        ))
    } else {
        Ok(Validation::Valid)
    }
}
```
