### ISSUE TITLE
DateSelect default help message incorrect ?

### ISSUE THREAD

**Issue by Cyrix126** [mikaelmello/inquire#220]
Hello, the default help message for dateselect is "arrows to move, []{} move months and years, enter to select".
Shouldn't it be "arrows to move, ctrl move months and years, enter to select" ?

It did get changed in commit 2575ad1.
Defined in inquire/inquire/src/prompts/dateselect/mod.rs

**Comment by Cyrix126** [comment]
oh I realized that controls have changed.

**Comment by mikaelmello** [comment]
hey @Cyrix126,

yeah, I realized the ctrl+arrows story got very tricky when I tested it across different terminal emulators and OSes.

I figured plain ascii keys would fare better in general, but if someone intuitively tries to navigate with ctrl+arrows, and their terminal does send this input to us, we'll still interpret it as before

let me know if that's a reasonable solution for you, otherwise I'm happy to look for new ones
