### ISSUE TITLE
Global/default add value

### ISSUE THREAD

**Issue by stacksjb** [mikaelmello/inquire#254]
**Is your feature request related to a problem? Please describe.**
I'm working on a stacked menu app using inquire, which works very well. However, in order to allow forward/backward (to sub menu/previous menu), I have to explicitly add a back option to each menu.

**Describe the solution you'd like**
I'd like to somehow be able to add a back or default menu option(s) to every menu, by default and/or globally

Instead, I have to do something like:
`
menu_options.push("q. Exit".to_string());
`
On every single menu.

**Describe alternatives you've considered**
Manually adding to each stage is the default workaround

**Comment by mikaelmello** [comment]
Hi @stacksjb , sorry for the delay.

I think that adding this kind of global param would bring a lot of complexity and global state, to a place where there is a little too much already imo.

The `skippable` was intended to help users who instinctively press `esc` to leave (e.g. optional fields). It might be a good method to handle that path (`Ok(None)` rather than `Err(OperationCanceled)`, but I'm afraid that your current solution is the best I can think of in terms of giving an exit path to the users.
