### ISSUE TITLE
less verbosity in ui::Color::Rgb{...}

### ISSUE THREAD

**Issue by adsick** [mikaelmello/inquire#41]
I suggest replacing it with ui::Color::Rgb(u8, u8, u8)

**Comment by mikaelmello** [comment]
I agree it has its benefits. Using a struct provides better readability when reading the values (e.g. `color.r` instead of `color.0`), but I think only the underlying terminal library actually reads these values, while we create them. While your suggestion makes it much less verbose to create them :)

Would you be willing to make a PR?

**Comment by adsick** [comment]
Oh, I didn't think about ```color.r ``` that's true. Idk, I'm kinda busy...

**Comment by mikaelmello** [comment]
Both your points are perfect to me. It _can_ get cumbersome on pattern matching and the like but I quite like to be explicit as well. Let's go with the static method.
