### ISSUE TITLE
Allow items for `Select` that do not necessary implement `Display` but with an appropiate formatter.

### ISSUE THREAD

**Issue by mainrs** [mikaelmello/inquire#42]
My use-case: I want to select over a tuple of values `(String, CustomStruct)`. The formatted message should be `tuple.0 + tuple.1.description`. The whole struct doesn't implement `Display`, but the select dialog should use the struct's description field.

Currently that doesn't seem to be possible. Maybe lowering the bounds on `T` or making a change to `Select` would allow this? For example:

```rust
pub struct Select<'a, T, U: Display> {
    pub options: Vec<T>,
    pub item_formatter: &'a Fn(T) -> U,
}
```

Then the default item formatter could operate on `T: Display` and users could specify their own by setting the field?
This does require changing multiple parts of the code. I changed it to the idea above and had trouble fixing some compilation errors (probably due to limited knowledge about how the library works internally).

The problems that I find unergonomic is that:
1) Creating the items using `format!()` returns a `String` after calling `prompt()`. It's hard to map that value back to the original selected item.
2) Doing fuzzy search now also looks for partial matches inside the `CustomStruct.description` field. And I want to only have it look into the first tuple value `tuple.0`.

**Comment by adsick** [comment]
I fully agree on that, selecting over Strings is kinda bad

**Comment by mikaelmello** [comment]
Hey! Thanks for your suggestion, I'll first try to give you a solution and then later we can discuss if it is indeed a good one and think about possible changes!

When implementing the generalization of selectable prompts, I had planned to solve this problem via the new-type pattern. As a personal example, I have a struct which maps a db entity:

```rust
#[derive(AsChangeset, Identifiable, Insertable, Queryable, Serialize, PartialEq, Eq)]
#[table_name = "tag"]
#[changeset_options(treat_none_as_null = "true")]
pub struct Tag {
    pub id: Ulid,
    pub title: String,
    pub description: Option<String>,
}
```

Then, by using the new type pattern I was able to implement a nice implementation that has one single clear purpose: formatting tags for being selected in a prompt:

```rust
struct TagSelectView(Tag);

impl Display for TagSelectView {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::result::Result<(), Error> {
        write!(f, "{} ({})", self.0, self.1.description)?;

        if let Some(desc) = &self.0.description {
            write!(f, " ({:.40})", desc)?;
        }

        Ok(())
    }
}
```

On a first glance it looks like too much boilerplate code, but from my experience when trying different ways, it was basically the same amount of code used for a formatter, except for the `struct` and `impl` lines. But on the other hand I felt it did improve readability.

Finally, just as an example, I select tags with this static method:

```rust
pub struct TagSelector;

impl TagSelector {
    pub fn select_skippable_from(
        msg: &str,
        tags: Vec1<Tag>,
        help_msg: &str,
    ) -> Result<Option<Tag>> {
        let tags = tags.into_iter().map(TagSelectView).collect();
        let tag = inquire::Select::new(msg, tags)
            .with_help_message(help_msg)
            .prompt_skippable()?
            .map(|t| t.0);

        Ok(tag)
    }
}
```

---

In your personal example, it could be solved similarly:

```rust
struct CustomStructView(String, CustomStruct);

impl CustomStructView {
    fn filter(input: &str, obj: &CustomStructView, str_value: &str, idx: usize) -> bool {
        input.contains(&obj.0)
    }
}

impl Display for CustomStructView {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::result::Result<(), Error> {
        write!(f, "{} ({})", self.0, self.1.description)
    }
}

pub fn select(objs: Vec1<CustomStruct>) -> Result<CustomStruct> {
    let objs = tags.into_iter()
        .map(|cs| CustomStructView("something".to_string(), cs))
        .collect();
        
    inquire::Select::new("Select one please:", objs)
        .with_help_message("Help message")
        .with_filter(&CustomStructView::filter)
        .prompt()
        .map(|t| t.1)
}
```

Also, I just noticed that the way filters are implemented could be more ergonomic, probably a trait instead of a static function in this use-case, but we would lost the ability to define filters in closures. But that's something to be discussed in another issue.

**Comment by mainrs** [comment]
Such a simple solution that I couldn't think off yesterday! That does indeed work perfectly fine. I'll close this. I do think that the above is better solution!

**Comment by AstrickHarren** [comment]
what about a solution like this? 
```rust 
pub struct Formatted<'a, T: ?Sized> {
    fmt: &'a dyn Fn(&T) -> String,
    value: T,
}

impl<'a, T> Formatted<'a, T> {
    pub fn new(value: T, fmt: &'a impl Fn(&T) -> String) -> Self {
        Self { fmt, value }
    }
}

impl<T: ?Sized> Display for Formatted<'_, T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        (self.fmt)(&self.value).fmt(f)
    }
}

impl<T> Deref for Formatted<'_, T> {
    type Target = T;
    fn deref(&self) -> &Self::Target {
        &self.value
    }
}
```
so that in their case it can be 
```rust 
fn select(objs: Vec<(String, CustomStruct)>) {
    let objs = objs
        .into_iter()
        .map(|o| Formatted::new(o, &|o| format!("{}: {}", o.0, o.1.desc)))
        .collect();
    let select = Select::new("Select an object", objs).prompt().unwrap();
    // use select as if it were (String, CustomStruct)
    println!("{}", select.0);
}
```

It's not perfect though, because you can't manually deref `select` as a box, because apparently box is kinda special.
