### ISSUE TITLE
The prompt don't work for me when I test in bash for windows terminal.

### ISSUE THREAD

**Issue by kiki407** [mikaelmello/inquire#50]
When using in bash for windows (https://gitforwindows.org/) the prompt freeze and don't let me enter a value.
It works in Powershell and cmd.
I am not sure what information I should provide. Let me know how I can help.

**Comment by mikaelmello** [comment]
Hi @kiki407, unfortunately this isn't an easy problem to fix due to the nature of how terminals like git bash work...

You can read more details here: https://github.com/crossterm-rs/crossterm/issues/580

A direction we _could_ go would be to have some sort of compatibility mode that would detect this scenario and render the prompts differently. Not sure how possible this is but it would require some work

**Comment by kiki407** [comment]
Thanks for the reply.
Fair enough.

**Comment by mikaelmello** [comment]
Closing this, at least until we have more tools at our disposal to fix it
