### ISSUE TITLE
Add prompts for common type?

### ISSUE THREAD

**Issue by rongcuid** [mikaelmello/inquire#72]
**Is your feature request related to a problem? Please describe.**
Right now, creating prompt for common types like `i64` is very verbose, especially when default values are involved, which somehow needs a formatting function provided with the value.

**Describe the solution you'd like**
Include prompts for common values, preferably for all types implementing `TryFrom<&str>` or equivalent.

**Describe alternatives you've considered**
Give some additional methods in `Text` so that it can parse values/validate/etc.

**Additional context**

**Comment by mikaelmello** [comment]
hey @rongcuid, can you provide a code sample of what you consider needing improvements? the `i64` prompt you mentioned for example, and something that imlpements `TryFrom<&str>`

**Comment by rongcuid** [comment]
For instance, for something like:

```
CustomType::<i64>::new("Prompt")
        .with_default((0, &|i| format!("{}", i)))
        .prompt()?;
```

Firstly, there is already a `.with_formatter` method, so I don't understand why it needs another formatter for the default value.

I looked a bit more and it does seem like I don't have to provide a parser for every type,  so functionality like the `TryFrom<&str>` might already be covered. 

However, if I want validation, things get complicated:

```
CustomType::<f64>::new("Prompt")
        .with_parser(&|s| {
            let x = s.parse::<f64>().map_err(|_| ())?;
            if x > 0. {
                Ok(x)
            } else {
                Err(())
            }
        })
        .with_formatter(&|i| format!("{:.0}", i))
        .with_error_message("Need >0")
        .prompt()?;
```

Maybe provide this?

```
CustomType::<i64>::new("").validate(|x| x > 0)// ...
```

**Comment by mikaelmello** [comment]
>Firstly, there is already a .with_formatter method, so I don't understand why it needs another formatter for the default value.

Great point, will change this.

>I looked a bit more and it does seem like I don't have to provide a parser for every type, so functionality like the TryFrom<&str> might already be covered.

Yeah that was my thought but I was wondering if I had missed something, a long time since I created this :D

>However, if I want validation, things get complicated

Good point as well, this should indeed be implemented.

---

Also, on this comment here:

> Give some additional methods in Text so that it can parse values/validate/etc.

I've thought a bit about it but:

- There already is support for validators, so you can already validate (after parsing yourself) any inputs there.
- Implementing support for the prompt itself parsing these values and returning these custom types would add generics complexity for the Text prompt, kind of sacrificing the, as I understand, most common use case.

If there is way to make the Text prompt return custom types while "not breaking" the current API I'd certainly go for it.

**Comment by rongcuid** [comment]
Perhaps just `.map()`? Or if more complicated, `.try_map()`?

**Comment by mikaelmello** [comment]
Hey, I implemented your more straightforward suggestions that should make your life a little easier with CustomType prompts now :)

As for porting Text to allow for custom types, it is going to be tricky, I'll create a discussion to not forget about it but there are other changes that I am prioritizing first atm. If you feel like it I'd be happy to seriously consider a PR.
